### ISSUE TITLE
Get-OpenADWhoAmi should return a richer object.

### ISSUE THREAD

**Issue by jdhitsolutions** [jborean93/PSOpenAD#27]
I recognize the value in `Get-OpenADWhoAmi` for troubleshooting. But from a PowerShell perspective, I'd encourage you to either modify the output to be just the username. Right now, I get a string like `u:COMPANY\ArtD`. If I want to save this to a variable and use for other testing, I have to parse the string. Although I'd prefer a richer object. Give me the name. Give me the authentication value. Show the LDAP uri.   I'm thinking ahead when maybe a help desk tech is trying to use this module but encountering errors. They ask for support and I tell them to run `Get-OpenADWhoAmi`. The richer object helps me better troubleshoot the problem.  I realize I could also ask the tech to run `Get-OpenADSession` but it would be nicer to have a single, rich object to work with.

**Comment by jborean93** [comment]
That's a good point. I can return an object that contains the session details from this request to provide more information rather than just the result of the Whoami extended request. I'm not sure about parsing the return string though, this is returned directly from AD/LDAP and while I've not seen any other prefix than `u:` being used I'm not sure if that's always going to be there. It probably doesn't hurt to just have both and hide the raw value from the default property set.

**Comment by jborean93** [comment]
The PR https://github.com/jborean93/PSOpenAD/pull/30 should fix this problem for you. By default it will show the parsed username, ldap uri, domain controller dns name, and the authentication type used for the session. The raw value is still present but hidden by default in the default display set.
