### ISSUE TITLE
Get-OpenADComputer should have a default LDAP Filter

### ISSUE THREAD

**Issue by jdhitsolutions** [jborean93/PSOpenAD#29]
If a user runs a command like this:

```powershell
Get-OpenADComputer -Server dom1 -SearchBase "OU=Domain Controllers,DC=Company,DC=pri"
```
It is pretty clear they want to list all computers in the OU.  But instead, you get prompted for an LDAP Filter. Shouldn't this default to something like `objectcategory=computer`. Don't assume the users of this module will have LDAP experience. Or you need to make that very clear in the documentation.

This also applies to `Get-OpenADUser`.

![image](https://user-images.githubusercontent.com/12089920/173441111-9d87aa36-1576-4093-8b68-cbb4bed0fd86.png)

**Comment by jborean93** [comment]
Looks like I need to tweak the parameter sets to allow this. The default behaviour is for `Get-OpenAD*` to automatically apply an LDAP filter for the object it is querying but the problem in this case is adding `-SearchBase` (or `-SearchScope`) is selecting the `LDAPFilter` parameter set where `-LDAPFilter` is set as mandatory hence the prompt. Will have to fix it up so applies that default filter in cases like this instead of being mandatory.
