### ISSUE TITLE
Get-OpenADComputer: LastLogonTimestamp blank if requested directly via -Property

### ISSUE THREAD

**Issue by JustinGrote** [jborean93/PSOpenAD#82]
![image](https://github.com/jborean93/PSOpenAD/assets/15258962/fc1440f6-2340-4193-aa0a-a40487023636)

**Comment by jborean93** [comment]
Thanks for the bug report, it looks like I was use a case sensitive check when building the final AD object so that when it was getting the value `LastLogonTimestamp` as requested by `-Property` it failed to match `lastLogonTimestamp` that was returned by the server. The PR https://github.com/jborean93/PSOpenAD/pull/83 should solve this issue.
